/**
 * FASE 3 — Test Generator
 *
 * Reads ENDPOINT_SPECS and generates Vitest test stubs for spec-validator
 * integration into backend/src/__tests__/generated/.
 *
 * Usage:
 *   npx tsx scripts/generate-tests.ts
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { ENDPOINT_SPECS } from '../specs/endpoints/index';
import type { EndpointSpec, FieldSchema } from '../specs/types';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, '../src/__tests__/generated');

function isFieldSchema(v: unknown): v is FieldSchema {
  return typeof v === 'object' && v !== null && 'required' in v;
}

function buildMockBody(spec: EndpointSpec): Record<string, unknown> {
  const body: Record<string, unknown> = {};
  for (const [field, def] of Object.entries(spec.input)) {
    if (!isFieldSchema(def)) continue;
    if (!def.required) continue;
    if (def.constraints?.some((c) => c.includes('path param') || c.includes('query param'))) continue;
    if (def.type === 'file' || def.type === 'file[]') continue;

    if (def.type === 'number') body[field] = 1;
    else if (def.type === 'boolean') body[field] = true;
    else if (def.type === 'array') body[field] = [];
    else if (def.type === 'enum' && def.constraints?.[0]) {
      const firstOption = def.constraints[0].split('|')[0].trim().replace(/'/g, '');
      body[field] = firstOption;
    } else if (def.type === 'string') {
      if (def.constraints?.some((c) => c.includes('uuid'))) {
        body[field] = '00000000-0000-0000-0000-000000000001';
      } else {
        body[field] = `test_${field}`;
      }
    } else {
      body[field] = `test_${field}`;
    }
  }
  return body;
}

function fillPathParams(p: string): string {
  return p.replace(/:([a-zA-Z]+)/g, '00000000-0000-0000-0000-000000000001');
}

function main() {
  if (!fs.existsSync(OUT_DIR)) fs.mkdirSync(OUT_DIR, { recursive: true });

  const results: string[] = [];

  for (const rawSpec of ENDPOINT_SPECS) {
    const spec = rawSpec as EndpointSpec;
    const method = spec.method.toLowerCase();
    if (!['post', 'put', 'patch'].includes(method)) continue;

    const requiredFields = Object.entries(spec.input)
      .filter(
        ([, def]) =>
          isFieldSchema(def) &&
          def.required &&
          def.type !== 'file' &&
          def.type !== 'file[]' &&
          !def.constraints?.some((c) => c.includes('path param') || c.includes('query param')),
      )
      .map(([k]) => k);

    if (requiredFields.length === 0) continue;

    const fullBody = buildMockBody(spec);
    const v1Path = `/v1${fillPathParams(spec.path)}`;

    const missingTests = requiredFields
      .map((field) => {
        const bodyWithout = { ...fullBody };
        delete bodyWithout[field];
        return `
  it('retorna 422 quando ${field} está ausente', async () => {
    const res = await request(app)
      .${method}('${v1Path}')
      .set('Content-Type', 'application/json')
      .send(${JSON.stringify(bodyWithout)});

    expect(res.status).toBe(422);
    expect(res.body.spec).toBe('${spec.name}');
    expect(res.body.campos_ausentes).toContain('Campo obrigatório ausente: "${field}"');
  });`;
      })
      .join('\n');

    const allMissingTest = `
  it('retorna 422 quando body está vazio', async () => {
    const res = await request(app)
      .${method}('${v1Path}')
      .set('Content-Type', 'application/json')
      .send({});

    expect(res.status).toBe(422);
    expect(res.body.campos_ausentes).toHaveLength(${requiredFields.length});
  });`;

    const errorTests = (spec.errors ?? [])
      .filter((e) => e.statusCode >= 400)
      .slice(0, 2)
      .map(
        (e) => `
  it.skip('${e.code}: ${e.message}', async () => {
    // TODO: setup mock for this error — expected status ${e.statusCode}
  });`,
      )
      .join('\n');

    const testContent = `// AUTO-GENERATED by scripts/generate-tests.ts — do not edit manually
// Source spec: specs/endpoints — ${spec.name}
// To regenerate: npm run spec:gen-tests
import { describe, it, expect, beforeEach, vi } from 'vitest';
import request from 'supertest';

vi.mock('../../utils/prisma', () => ({
  prisma: {
    usuario: { findFirst: vi.fn(), findUnique: vi.fn(), create: vi.fn() },
    produto: { findMany: vi.fn(), findUnique: vi.fn(), create: vi.fn(), update: vi.fn(), delete: vi.fn() },
    loja: { findUnique: vi.fn(), findMany: vi.fn(), findFirst: vi.fn(), create: vi.fn() },
    pedido: { findMany: vi.fn(), findUnique: vi.fn(), create: vi.fn() },
    supportTicket: { findUnique: vi.fn(), findMany: vi.fn(), create: vi.fn(), update: vi.fn() },
    enderecoUsuario: { findMany: vi.fn(), findUnique: vi.fn(), create: vi.fn(), count: vi.fn() },
    avaliacaoLoja: { findUnique: vi.fn(), create: vi.fn() },
    dispositivoPush: { upsert: vi.fn(), updateMany: vi.fn() },
    chatPedido: { findUnique: vi.fn(), findMany: vi.fn() },
    chatMensagemPedido: { create: vi.fn(), updateMany: vi.fn(), count: vi.fn() },
    variacaoProduto: { findMany: vi.fn() },
    pagamento: { create: vi.fn() },
    $transaction: vi.fn(),
  },
}));
vi.mock('../../utils/bcrypt', () => ({ hashSenha: vi.fn().mockResolvedValue('$2b$10$hashed'), compararSenha: vi.fn().mockResolvedValue(true) }));
vi.mock('../../utils/jwt', () => ({ gerarToken: vi.fn().mockReturnValue('mock.jwt.token'), gerarRefreshToken: vi.fn().mockReturnValue('mock.refresh.token'), verificarRefreshToken: vi.fn().mockReturnValue({ id: 'uid', tipo: 'usuario' }) }));
vi.mock('../../lib/rateLimiter', () => ({ authLimiter: (_r: unknown, _s: unknown, n: () => void) => n(), chatLimiter: (_r: unknown, _s: unknown, n: () => void) => n() }));
vi.mock('../../lib/logger', () => ({ logger: { info: vi.fn(), debug: vi.fn(), error: vi.fn(), warn: vi.fn() } }));
vi.mock('../../utils/cors', () => ({ corsOptions: {} }));
vi.mock('../../utils/socket', () => ({ getIo: vi.fn(() => ({ to: vi.fn(() => ({ emit: vi.fn() })) })), emitPedidoNovo: vi.fn(), emitPedidoAtualizado: vi.fn(), getEntregadorLocalizacao: vi.fn(), emitTicketMensagem: vi.fn(), emitChatMensagem: vi.fn() }));
vi.mock('../../lib/pushNotifications', () => ({ notificarPedidoNovo: vi.fn().mockResolvedValue(undefined) }));
vi.mock('../../middleware/auth', () => { const pass = (_r: unknown, _s: unknown, n: () => void) => n(); return { authMiddleware: pass, authUsuario: pass, authLojista: pass, authEntregador: pass, authColaborador: pass, authLojistaOrColaborador: pass, authAdmin: pass, requirePapel: () => pass }; });

const { app } = await import('../../app');

describe('${spec.name} — spec validation (generated)', () => {
  beforeEach(() => vi.clearAllMocks());
${missingTests}
${allMissingTest}
${errorTests}
});
`;

    const outFile = path.join(OUT_DIR, `${spec.name}.generated.test.ts`);
    fs.writeFileSync(outFile, testContent);
    results.push(`  ✓ ${spec.name}.generated.test.ts`);
  }

  console.log(`\nGenerated ${results.length} test files in src/__tests__/generated/:\n${results.join('\n')}\n`);
}

main();
