/**
 * FASE 2 helper — Agent Context Generator
 *
 * Reads ENDPOINT_SPECS and regenerates src/lib/agent-context.ts.
 *
 * Usage:
 *   npx tsx scripts/generate-agent-context.ts
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { ENDPOINT_SPECS } from '../specs/endpoints/index';
import type { EndpointSpec, FieldSchema } from '../specs/types';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT_FILE = path.resolve(__dirname, '../src/lib/agent-context.ts');

function isFieldSchema(v: unknown): v is FieldSchema {
  return typeof v === 'object' && v !== null && 'required' in v;
}

function summarizeFields(input: Record<string, FieldSchema | Record<string, unknown>>): string {
  const required: string[] = [];
  const optional: string[] = [];

  for (const [field, def] of Object.entries(input)) {
    if (!isFieldSchema(def)) continue;
    if (def.constraints?.some((c) => c.includes('path param') || c.includes('query param'))) continue;
    if (def.type === 'file' || def.type === 'file[]') continue;

    const constraint = def.constraints?.find((c) => !c.includes('param'));
    const label = constraint ? `${field}(${constraint})` : field;

    if (def.required) required.push(label);
    else optional.push(`${field}?`);
  }

  return [...required, ...optional].join(', ') || '—';
}

function main() {
  const groups: Record<string, string[]> = {};

  for (const rawSpec of ENDPOINT_SPECS) {
    const spec = rawSpec as EndpointSpec;
    const tag = spec.path.split('/').filter(Boolean)[0] ?? 'misc';
    if (!groups[tag]) groups[tag] = [];

    const pathDisplay = spec.path;
    const fields = summarizeFields(spec.input);
    const authLabel = spec.auth === 'none' ? 'público' : String(spec.auth);
    const line = `- ${spec.method} /v1${pathDisplay} [${authLabel}] — ${fields}`;
    groups[tag].push(line);
  }

  const sections = Object.entries(groups)
    .map(([tag, lines]) => `### ${tag}\n${lines.join('\n')}`)
    .join('\n\n');

  const content = `/**
 * Compact spec summaries injected into the Aju AI agent system prompt.
 * AUTO-GENERATED by scripts/generate-agent-context.ts — do not edit manually.
 * Regenerate: npm run spec:gen-agent-context
 */

export const AGENT_SPEC_CONTEXT = \`
## API disponível para referência

${sections}

### Validações importantes
- CPF: 11 dígitos com validação de dígitos verificadores
- CNPJ: 14 dígitos com validação
- Senha forte: mín 8 chars, maiúscula, minúscula, número, símbolo
- PIX: desconto automático de 5% no total do pedido
- Estoque: decrementado atomicamente ao criar pedido; produto desativado ao chegar em zero
- CEP: validado via ViaCEP antes de salvar endereço
\`.trim();
`;

  fs.writeFileSync(OUT_FILE, content);
  console.log(`\nAgent context written to ${OUT_FILE}\n`);
}

main();
