/**
 * Compact spec summaries injected into the Aju AI agent system prompt.
 * AUTO-GENERATED by scripts/generate-agent-context.ts — do not edit manually.
 * Regenerate: npm run spec:gen-agent-context
 */

export const AGENT_SPEC_CONTEXT = `
## API disponível para referência

### auth
- POST /v1/auth/usuario/registrar [público] — nome(min 2 caracteres), cpf(CPF válido (dígitos verificadores)), telefone(formato +55XXXXXXXXXXX (13 dígitos após +55)), email(email válido), senha(min 8 caracteres)
- POST /v1/auth/usuario/login [público] — cpf(aceita formatado ou somente dígitos), senha(min 1 caractere)
- POST /v1/auth/lojista/registrar [público] — cnpj(CNPJ válido (14 dígitos)), nomeResponsavel(min 2 caracteres), email(email válido), senha(min 8 chars), telefone(formato +55XXXXXXXXXXX)
- POST /v1/auth/lojista/login [público] — senha, identificador?, cnpj?
- POST /v1/auth/entregador/registrar [público] — nome(min 2 caracteres), cpf(CPF válido), telefone(formato +55XXXXXXXXXXX), email(email válido), senha(min 8 chars), tipoTransporte('bike' | 'moto' | 'carro')
- POST /v1/auth/refresh [público] — refreshToken(JWT válido não expirado)

### pedidos
- POST /v1/pedidos [usuario] — lojaId(uuid), enderecoEntregaId(uuid), metodoPagamento('pix' | 'cartao'), itens(min 1 item), obs?
- GET /v1/pedidos [usuario] — —
- GET /v1/pedidos/:id [usuario] — —
- POST /v1/pedidos/:id/rastrear [usuario] — —

### produtos
- POST /v1/produtos [lojista] — lojaId(uuid), nome(min 2 caracteres), descricao, preco(positivo (> 0)), estoque(int), imagemUrl(URL válida), categoria, tags?, destaque?
- GET /v1/produtos/:id [público] — —
- PUT /v1/produtos/:id [lojista] — nome?, descricao?, preco?, estoque?, disponivel?, destaque?, categoria?, tags?

### lojista
- PUT /v1/lojista/produtos/:id [lojista] — nome?, descricao?, preco?, estoque?, categoria?, disponivel?, imagensExistentes?, variacoes?
- PATCH /v1/lojista/pedidos/:id/status [lojista] — —
- GET /v1/lojista/lojas/:id/dashboard [lojista] — —

### lojas
- GET /v1/lojas [público] — —
- GET /v1/lojas/:id [público] — —
- GET /v1/lojas/:id/produtos [público] — disponivel?

### tickets
- GET /v1/tickets [usuario] — —
- POST /v1/tickets/:id/mensagens [usuario] — texto(min 1 caractere (trim))

### enderecos
- POST /v1/enderecos [usuario] — apelido(min 1 caractere), rua(min 1 caractere), numero(min 1 caractere), bairro(min 1 caractere), cep(exatamente 8 dígitos numéricos), cidade(min 1 caractere), complemento?, lat?, lng?, geoSource?

### avaliacoes
- POST /v1/avaliacoes [usuario] — pedidoId(uuid), nota(int), comentario?

### entregador
- POST /v1/entregador/corridas/:pedidoId/aceitar [entregador] — —
- POST /v1/entregador/corridas/:pedidoId/confirmar-entrega [entregador] — codigo(min 1 caractere)
- POST /v1/entregador/heartbeat [entregador] — lat(float), lng(float)

### Validações importantes
- CPF: 11 dígitos com validação de dígitos verificadores
- CNPJ: 14 dígitos com validação
- Senha forte: mín 8 chars, maiúscula, minúscula, número, símbolo
- PIX: desconto automático de 5% no total do pedido
- Estoque: decrementado atomicamente ao criar pedido; produto desativado ao chegar em zero
- CEP: validado via ViaCEP antes de salvar endereço
`.trim();
